src/Entity/Party.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PartyRepository")
 *  * @Vich\Uploadable
 */
class Party
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @Vich\UploadableField(mapping="picture", fileNameProperty="picture")
     * @var File
     */
    private $pictureFile;

    /**
     * @return \DateTime|null
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime|null $updatedAt
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }



    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="datetime")
     */
    private $started_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $ended_at;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="parties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Travel", mappedBy="party")
     */
    private $travels;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->travels = new ArrayCollection();
        $this->setCreatedAt(new \DateTime());
        $this->setStartedAt(new \DateTime());
        $this->setEndedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(\DateTimeInterface $ended_at): self
    {
        $this->ended_at = $ended_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return File
     */
    public function getPictureFile(): ?File
    {
        return $this->pictureFile;
    }

    /**
     * @param File $pictureFile
     */
    public function setPictureFile(File $pictureFile): void
    {
        $this->pictureFile = $pictureFile;
        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($pictureFile) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }

    }

    /**
     * @return Collection|Travel[]
     */
    public function getTravels(): Collection
    {
        return $this->travels;
    }

    public function addTravel(Travel $travel): self
    {
        if (!$this->travels->contains($travel)) {
            $this->travels[] = $travel;
            $travel->setParty($this);
        }

        return $this;
    }

    public function removeTravel(Travel $travel): self
    {
        if ($this->travels->contains($travel)) {
            $this->travels->removeElement($travel);
            // set the owning side to null (unless already changed)
            if ($travel->getParty() === $this) {
                $travel->setParty(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->name;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }


}

src/Form/PartyType.php
<?php

namespace App\Form;

use App\Entity\Party;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PartyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array('label'=>'Nom : ',  'required'=> true))
            ->add('pictureFile', VichImageType::class, array('label'=>'Image', 'required'=> true))
            ->add('city', TextType::class, array('label'=>'Ville',  'required'=> true))
            ->add('started_at', DateTimeType::class, array('label'=>'Débute le :'))
            ->add('ended_at',DateTimeType::class, array('label'=>'Termine le :'))
            ->add('description', TextareaType::class, array('label'=>'Description'))
//            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Party::class,
        ]);
    }
}

src/Controller/PartyController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Party;
use App\Entity\Travel;
use App\Form\PartyType;
use App\Repository\PartyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class PartyController extends AbstractController
{
    /**
     * @Route("/party", name="party_index", methods={"GET"})
     */
    public function index(PartyRepository $partyRepository): Response
    {

        return $this->render('party/index.html.twig', [

            'parties' => $partyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/party/new", name="party_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $party = new Party();
        $party->setUser($this->getUser());
        $form = $this->createForm(PartyType::class, $party);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($party);
            $entityManager->flush();

            return $this->redirectToRoute('homepage/');
        }

        return $this->render('party/new.html.twig', [
            'party' => $party,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/party/{id}", name="party_show", methods={"GET"})
     */
    public function show(Party $party): Response
    {
        $travel = $this->getDoctrine()->getRepository(Travel::class)->findBy([], ['party'=>'desc']);
        $aller= $this->getDoctrine()->getRepository(Category::class)->findOneBy(['label'=>Category::ALLER]);
        $retour= $this->getDoctrine()->getRepository(Category::class)->findOneBy(['label'=>Category::RETOUR]);
        $allertravels = $this->getDoctrine()->getRepository(Travel::class)->findByCategory($party, $aller,6);
        $retourtravels = $this->getDoctrine()->getRepository(Travel::class)->findByCategory($party, $retour,6);

        dump($allertravels);

        return $this->render('party/show.html.twig', [

            'party' => $party,
            'travels' =>$travel,
            "allers"=>$allertravels,
            "retours"=>$retourtravels,

        ]);
    }

    /**
     * @Route("/party/{id}/edit", name="party_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Party $party): Response
    {
        $form = $this->createForm(PartyType::class, $party);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('party_index', [
                'id' => $party->getId(),
            ]);
        }

        return $this->render('party/edit.html.twig', [
            'party' => $party,

            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/party/{id}", name="party_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Party $party): Response
    {
        if ($this->isCsrfTokenValid('delete' . $party->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($party);
            $entityManager->flush();
        }

        return $this->redirectToRoute('party_index');
    }

    /**
     * @Route("/search-results", name="search", methods="GET")
     */
    public function searchQuery(Request $request)
    {
        $uq = $request->get('search-query');
        if ($uq === "") {
            $parties = $this->getDoctrine()->getRepository(Party::class)->findAll();
            return $this->render('search/index.html.twig', ['parties' => $parties]);
        } else {
            $parties = $this->getDoctrine()->getRepository(Party::class)->searchBy($uq);
            return $this->render('search/index.html.twig', ['parties' => $parties]);
        }
    }
}

templates/party/_delete_form.html.twig
<form method="post" action="{{ path('party_delete', {'id': party.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ party.id) }}">
    <button class="btn">Delete</button>
</form>

templates/party/_form.html.twig
<div class="container">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}
</div>

templates/party/card.html.twig
<div class="card my-5" style="width: 18rem;">
    <div class="card-body">
        <h3 class="card-title">{{ party.name }}</h3>
        <h6 class="card-subtitle mb-2 text-muted">Lieu : {{ party.city }}</h6>
        <h6>Date & heure: {{ party.startedAt|date('d/m/Y H:i') }}</h6>
        <a class="btn btn-success" href="{{ path('party_show',{'id': party.id}) }}">voir plus</a>

    </div>
</div>

templates/party/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Party{% endblock %}

{% block body %}
    <h1>Edit Party</h1>

    {{ include('party/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('party_index') }}">back to list</a>

    {{ include('party/_delete_form.html.twig') }}
{% endblock %}

templates/party/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Party index{% endblock %}

{% block body %}
    <h1>Party index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Picture</th>
                <th>City</th>
                <th>Started_at</th>
                <th>Ended_at</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for party in parties %}
            <tr>
                <td>{{ party.id }}</td>
                <td>{{ party.name }}</td>
                <td>{{ party.picture }}</td>
                <td>{{ party.city }}</td>
                <td>{{ party.startedAt ? party.startedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ party.endedAt ? party.endedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ party.description }}</td>
                <td>
                    <a href="{{ path('party_show', {'id': party.id}) }}">show</a>
                    <a href="{{ path('party_edit', {'id': party.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('party_new') }}">Create new</a>
{% endblock %}

templates/party/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Party{% endblock %}

{% block body %}
    <h1>Création d'un évenement</h1>

    {{ include('party/_form.html.twig') }}

{% endblock %}

templates/party/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Party{% endblock %}

{% block body %}




<div class="container">

    <h1 class="partyTitle">{{ party.name }}</h1>

    <img class="img-fluid rounded mx-auto d-block" src="{{ asset('uploads/' ~ party.picture) }}" alt="{{ party.name }}">
    <div class="row">
<div class="col-md-4"></div>
    <div class="partyInfo col-md-4">
        <p>du : {{ party.startedAt|date('d-m ') }} au {{ party.endedAt|date('d-m-Y ') }}</p>

        <p class="partyCity">{{ party.city }}</p>
    </div>
    <div class="col-md-4"></div>



<div class="col-md-4"></div>
<div class="col-md-4"><p class="partyDescription">{{ party.description }}</p></div>
<div class="col-md-4"></div>

    </div>
</div>



    <h4>Trajet aller</h4>
    <div class="aller ">
        {% for aller in allers %}
            <a href="{{ path('travel_show', {'id':aller.id}) }}">
                <article class="col-md-3 cardaller" >
                    {% include 'travel/cardaller.html.twig' with {'travel' : aller} only %}
                </article>
            </a>
        {% endfor %}
    </div>
    <h4>Trajet retour</h4>
    <div class="retour ">
        {% for retour in retours %}
            <a href="{{ path('travel_show', {'id':retour.id}) }}">

                <article class="col-md-3 cardretour">
                    {% include 'travel/cardretour.html.twig'with {'travel' : retour} only %}
                </article>
            </a>
        {% endfor %}

    </div>

    <a class="btn btn-primary" role="button" href="{{ path('travel_new',{'id': party.id}) }}">Proposer un trajet</a>


    {#<table class="table">#}
        {#<tbody>#}
            {#<tr>#}
                {#<th>Id</th>#}
                {#<td>{{ party.id }}</td>#}
            {#</tr>#}
            {#<tr>#}
                {#<th>Name</th>#}
                {#<td>{{ party.name }}</td>#}
            {#</tr>#}
            {#<tr>#}
                {#<th>Picture</th>#}
                {#<td>{{ party.picture }}</td>#}
            {#</tr>#}
            {#<tr>#}
                {#<th>City</th>#}
                {#<td>{{ party.city }}</td>#}
            {#</tr>#}
            {#<tr>#}
                {#<th>Started_at</th>#}
                {#<td>{{ party.startedAt ? party.startedAt|date('Y-m-d H:i:s') : '' }}</td>#}
            {#</tr>#}
            {#<tr>#}
                {#<th>Ended_at</th>#}
                {#<td>{{ party.endedAt ? party.endedAt|date('Y-m-d H:i:s') : '' }}</td>#}
            {#</tr>#}
            {#<tr>#}
                {#<th>Description</th>#}
                {#<td>{{ party.description }}</td>#}
            {#</tr>#}
        {#</tbody>#}
    {#</table>#}

    {#<a href="{{ path('party_index') }}">back to list</a>#}

    {#<a href="{{ path('party_edit', {'id': party.id}) }}">edit</a>#}

    {#{{ include('party/_delete_form.html.twig') }}#}
{% endblock %}