src/Entity/Travel.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TravelRepository")
 */
class Travel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="datetime")
     */
    private $started_at;

    /**
     * @ORM\Column(type="smallint")
     */
    private $nb_user;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Party", inversedBy="travels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $party;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="travels")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="travel")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="travel")
     */
    private $bookings;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="travels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->setCreatedAt(new \DateTime());
        $this->setStartedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getNbUser(): ?int
    {
        return $this->nb_user;
    }

    public function setNbUser(int $nb_user): self
    {
        $this->nb_user = $nb_user;

        return $this;
    }

    public function getPrice()
    {
        return $this->price;
    }

    public function setPrice($price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getParty(): ?Party
    {
        return $this->party;
    }

    public function setParty(?Party $party): self
    {
        $this->party = $party;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setTravel($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getTravel() === $this) {
                $message->setTravel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setTravel($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getTravel() === $this) {
                $booking->setTravel(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->getCity();
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
// controller pour calculer le nb place restante sur covoit
    public function getNbUsersLeft() {
        $nbLeft = $this->getNbUser();
        foreach ($this->getBookings() as $booking) {
            $nbLeft = $nbLeft - $booking->getNbTravelers();
        }
        return $nbLeft;
    }

public function getCreatedAt(): ?\DateTimeInterface
{
    return $this->createdAt;
}

public function setCreatedAt(\DateTimeInterface $CreatedAt): self
{
    $this->createdAt = $CreatedAt;

    return $this;
}



}

src/Controller/TravelController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\Message;
use App\Entity\Travel;
use App\Form\Travel1Type;
use App\Repository\MessageRepository;
use App\Repository\TravelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/travel")
 */
class TravelController extends AbstractController
{
    /**
     * @Route("/", name="travel_index", methods={"GET"})
     */
    public function index(TravelRepository $travelRepository): Response
    {

        return $this->render('travel/index.html.twig', [
            'travels' => $travelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="travel_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $travel = new Travel();
        $travel->setUser($this->getUser());
        $form = $this->createForm(Travel1Type::class, $travel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($travel);
            $entityManager->flush();

            return $this->redirectToRoute('homepage');
        }

        return $this->render('travel/new.html.twig', [
            'travel' => $travel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="travel_show", methods={"GET"})
     */
    public function show(Travel $travel): Response
    {
        $message = $this->getDoctrine()->getRepository(Message::class)->findBy(['travel'=>$travel]);
        $booking = $this->getDoctrine()->getRepository(Booking::class)->findBy(['travel'=>$travel]);

        return $this->render('travel/show.html.twig', [
            'travel' => $travel,
            'messages' => $message,
            'bookings'=>$booking
        ]);
    }

    /**
     * @Route("/{id}/edit", name="travel_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Travel $travel): Response
    {
        $form = $this->createForm(Travel1Type::class, $travel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('travel_index', [
                'id' => $travel->getId(),
            ]);
        }

        return $this->render('travel/edit.html.twig', [
            'travel' => $travel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="travel_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Travel $travel): Response
    {
        if ($this->isCsrfTokenValid('delete'.$travel->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($travel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('travel_index');
    }
}

templates/travel/_delete_form.html.twig
<form method="post" action="{{ path('travel_delete', {'id': travel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ travel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/travel/_form.html.twig
<div class="container">
{{ form_start(form) }}

    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Envoyer') }}</button>
{{ form_end(form) }}
</div>

templates/travel/cardaller.html.twig
<div class="card ">
    <div class="card-body">
        <h3 class="card-title">{{ travel.party }}</h3>
        <h6 class="card-subtitle mb-2 text-muted">Lieu de départ: {{ travel.city }}</h6>
        <h6>Date & heure: {{ travel.startedAt|date('d/m/Y H:i') }}</h6>
        <h6>Place(s) disponible(s): {{ travel.nbUsersLeft }}</h6>
        <h6>Tarifs: {{ travel.price }}</h6>
        <a class="btn btn-success" href="{{ path('travel_show', {'id':travel.id}) }}">voir plus</a>
    </div>
</div>

templates/travel/cardretour.html.twig
<div class="card" >
    <div class="card-body">
        <h3 class="card-title">{{ travel.city }}</h3>
        <h6 class="card-subtitle mb-2 text-muted">Lieu de départ: {{ travel.party }}</h6>
        <h6>Date & heure: {{ travel.startedAt|date('d/m/Y H:i') }}</h6>
        <h6>Place(s) disponible(s): {{ travel.nbUsersLeft }}</h6>
        <h6>Tarifs: {{ travel.price }}€</h6>
        <a class="btn btn-success" href="{{ path('travel_show', {'id':travel.id}) }}">voir plus</a>

    </div>
</div>

templates/travel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Travel{% endblock %}

{% block body %}
    <h1>Edit Travel</h1>

    {{ include('travel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('travel_index') }}">back to list</a>

    {{ include('travel/_delete_form.html.twig') }}
{% endblock %}

templates/travel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Travel index{% endblock %}

{% block body %}
    <h1>Travel index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>City</th>
                <th>Started_at</th>
                <th>Nb_user</th>
                <th>Nb_place encore dispo</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for travel in travels %}
            <tr>
                <td>{{ travel.id }}</td>
                <td>{{ travel.city }}</td>
                <td>{{ travel.startedAt ? travel.startedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ travel.nbUser }}</td>
                <td>{{ travel.nbUsersLeft }}</td>
                <td>{{ travel.price }}</td>
                <td>
                    <a href="{{ path('travel_show', {'id': travel.id}) }}">show</a>
                    <a href="{{ path('travel_edit', {'id': travel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('travel_new') }}">Create new</a>
{% endblock %}

templates/travel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Travel{% endblock %}

{% block body %}
    <div class="container">

    <h1>Proposer un trajet</h1>

    {{ include('travel/_form.html.twig') }}

    <a href="{{ path('travel_index') }}">back to list</a>
    </div>

{% endblock %}

templates/travel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Travel{% endblock %}

{% block body %}

    <div class="container travelParty col-md-3">
    <h3>{{ travel.category }}</h3>
    <h1>Ville : {{ travel.city }}</h1>
    <H2>Evenement : {{ travel.party }}</H2>
    <p>Conducteur: {{ travel.user }}</p>
    <p>Nombre de place restantes:{{ travel.nbUsersLeft }}</p>
    <p>Tarif par personne: {{ travel.price }}</p>
    </div>

    <div class="container">
        <h3>Messages:</h3>
        {% for message in messages %}
            <p>{{ message.user.firstname }}</p>
            <p>{{ message.title }}</p>
            <p>{{ message.content }}</p>
        {% endfor %}
            {% if app.user %}
            <span class="btn btn-outline-primary">{{ app.user.firstname }}</span>
            {{ render(controller('App\\Controller\\MessageController:new', {'id': travel.id}))}}
            {% else %}
                <h4>Pour reserver un trajet ou envoyer un message, veuillez vous connecter ou creer un compte</h4>
                <a class="btn btn-outline-primary" href="{{ path('app_login') }}">Se connecter</a>
                <a class="btn btn-outline-primary" href="{{ path('user_registration') }}">
                    <i class="fa fa-user-plus"></i>
                    Créer un compte
                </a>

            {% endif %}


    </div>


<div class="container">
    <h3>Reservations.</h3>
    {% for booking in travel.bookings %}
        <h1>Utilisateur : {{ booking.user }}</h1>
        <p>Nb de places reservées : {{ booking.nbTravelers }}</p>
    {% endfor %}
    {% if app.user and travel.nbUsersLeft>0 %}
        <div class="modal fade" id="Booking" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Reservation</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Veuillez saisir le nombre de passagers a reserver
                    </div>
                    <div class="modal-footer">
                        {{render(controller('App\\Controller\\BookingController:new', {'id': travel.id}))}}

                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Retour</button>
                    </div>
                </div>
            </div>
        </div>


        <a class="btn btn-success" data-toggle="modal" data-target="#Booking">Reserver</a>
        {% else %}
        <h1>Trajet complet</h1>
    {% endif %}

</div>




{% endblock %}